<?php

namespace App\Http\Controllers;


use App\Models\Tag_category;
use Facebook\Facebook;
use Illuminate\Http\Request;

class SearchController extends Controller
{
    public function searchTag(Request $request)
    {

        $word=$request->search;
        $fb = new Facebook([
            'app_id' => '1522624067942900',
            'app_secret' => 'd964790080176580274538dc800ed633',
            'default_graph_version' => 'v2.10',
        ]);
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v2.10/oauth/access_token?grant_type=fb_exchange_token&client_id=1522624067942900&client_secret=d964790080176580274538dc800ed633&fb_exchange_token=EAAVo0YqyOfQBAGYJKj77SKpHlGwXUXhNY7iXHFMH8qC70c5yuEqQyzSxwHyRRbuh1xsZCSLAp8D5VbNNr0eTRJza0xxwIhnTS6jSAYSpIbyJBDaoOnZB5mXqQgwJYJumbw2wz1CGjg1QMwKqS6ClDhRzTpx50w0ouj0v9U72nAd0GaN3Kb9NzjpuJ31bCGGOBVLZCAnB94brNgazaZCUSk3qqyow1MTWZCbpzuci0K60JvfXjAtTH');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        curl_close($ch);
        try {
            // Returns a `FacebookFacebookResponse` object
            $hashtag=$fb->get(
                "/ig_hashtag_search?user_id=17841432565366212&q=$word",
                'EAAVo0YqyOfQBAFhHapR3hOuYA1DtyRilB4Q2RaLngaGQeBXaS2OSGIZCZBYqx6zOSGZCtfZBxFVjX1wt0zrd6UmngS4RZC0EeH0bBpqqPxZCh6KuZCqq4CznNP8OZAmPP6rUMvx3zNsu03PdJOO2DyO67jPH4vvuJkrfAZB6sjbFzbZCRbppkfLRWg'

            );

            $tagged=$hashtag->getDecodedBody();

            foreach ($tagged as $tag) {
                foreach ($tag as $tagName) {
                    $taggedId=$tagName['id'];
                    $response = $fb->get(
                        "/$taggedId/top_media?user_id=17841432565366212&fields=id,media_type,comments_count,like_count,caption,media_url,permalink,timestamp",
                        'EAAVo0YqyOfQBAFhHapR3hOuYA1DtyRilB4Q2RaLngaGQeBXaS2OSGIZCZBYqx6zOSGZCtfZBxFVjX1wt0zrd6UmngS4RZC0EeH0bBpqqPxZCh6KuZCqq4CznNP8OZAmPP6rUMvx3zNsu03PdJOO2DyO67jPH4vvuJkrfAZB6sjbFzbZCRbppkfLRWg'
                    );
                }
            }
        } catch(FacebookExceptionsFacebookResponseException $e) {
            echo 'Graph returned an error: ' . $e->getMessage();
            exit;
        } catch(FacebookExceptionsFacebookSDKException $e) {
            echo 'Facebook SDK returned an error: ' . $e->getMessage();
            exit;
        }
        $data=$response->getDecodedBody();
        return Response($data);
    }
}
