<?php

namespace App\Http\Controllers;


use App\Models\Campaign;
use App\Models\Post;
use App\Models\Tag_category;
use App\Models\User;
use Facebook\Facebook;
use Illuminate\Http\Request;

class SearchController extends Controller
{
    public function searchTag(Request $request)
    {

        $word=$request->search;
        $fb = new Facebook([
            'app_id' => '1522624067942900',
            'app_secret' => 'd964790080176580274538dc800ed633',
            'default_graph_version' => 'v2.10',
        ]);
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v2.10/oauth/access_token?grant_type=fb_exchange_token&client_id=1522624067942900&client_secret=d964790080176580274538dc800ed633&fb_exchange_token=EAAVo0YqyOfQBAGYJKj77SKpHlGwXUXhNY7iXHFMH8qC70c5yuEqQyzSxwHyRRbuh1xsZCSLAp8D5VbNNr0eTRJza0xxwIhnTS6jSAYSpIbyJBDaoOnZB5mXqQgwJYJumbw2wz1CGjg1QMwKqS6ClDhRzTpx50w0ouj0v9U72nAd0GaN3Kb9NzjpuJ31bCGGOBVLZCAnB94brNgazaZCUSk3qqyow1MTWZCbpzuci0K60JvfXjAtTH');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        curl_close($ch);
        try {
            // Returns a `FacebookFacebookResponse` object
            $hashtag=$fb->get(
                "/ig_hashtag_search?user_id=17841432565366212&q=$word",
                'EAAVo0YqyOfQBAFhHapR3hOuYA1DtyRilB4Q2RaLngaGQeBXaS2OSGIZCZBYqx6zOSGZCtfZBxFVjX1wt0zrd6UmngS4RZC0EeH0bBpqqPxZCh6KuZCqq4CznNP8OZAmPP6rUMvx3zNsu03PdJOO2DyO67jPH4vvuJkrfAZB6sjbFzbZCRbppkfLRWg'

            );

            $tagged=$hashtag->getDecodedBody();

            foreach ($tagged as $tag) {
                foreach ($tag as $tagName) {
                    $taggedId=$tagName['id'];
                    $response = $fb->get(
                        "/$taggedId/top_media?user_id=17841432565366212&fields=id,media_type,comments_count,like_count,caption,media_url,permalink,timestamp",
                        'EAAVo0YqyOfQBAFhHapR3hOuYA1DtyRilB4Q2RaLngaGQeBXaS2OSGIZCZBYqx6zOSGZCtfZBxFVjX1wt0zrd6UmngS4RZC0EeH0bBpqqPxZCh6KuZCqq4CznNP8OZAmPP6rUMvx3zNsu03PdJOO2DyO67jPH4vvuJkrfAZB6sjbFzbZCRbppkfLRWg'
                    );
                }
            }
        } catch(FacebookExceptionsFacebookResponseException $e) {
            echo 'Graph returned an error: ' . $e->getMessage();
            exit;
        } catch(FacebookExceptionsFacebookSDKException $e) {
            echo 'Facebook SDK returned an error: ' . $e->getMessage();
            exit;
        }
//        $insta_id='CNo-rNwL1NL';
        $data=$response->getDecodedBody();
//        $your_url = "https://www.instagram.com/p/CNpKmG0jpNe/";
//        $api = file_get_contents("https://api.instagram.com/oembed?callback=&url=" . $your_url);
//        $media_id = json_decode($api,true)['media_id'];
//
//        dd($media_id);

        return Response($data);
//        if ($request->ajax()) {
//            $category = Tag_category::where('name', 'LIKE', '%' . $request->search . "%")->get();
//            if ($category) {
//                return Response($category);
//            }
//        }
    }
    public function search_campaign(Request $request){
        if ($request->ajax()) {
            $campaign = Campaign::where('hashtags', 'LIKE', '%' . $request->search . "%")->paginate(5);
            if ($campaign) {
                return Response($campaign);
            }
        }
    }
    public function searchName(Request $request){
        if ($request->ajax()) {
            $word=$request->search;
            $user=User::where('name', 'LIKE', '%' . $word . "%")->orWhere('last_name', 'LIKE', '%' . $word . "%")->paginate(5);
            if($user) {
                return Response($user);
            }
        }
    }
//    public function instagram_id_to_url($instagram_id){
//
//        $url_prefix = "https://www.instagram.com/p/";
//
//        if(!empty(strpos($instagram_id, '_'))){
//
//            $parts = explode('_', $instagram_id);
//            $instagram_id = $parts[0];
//
//            $userid = $parts[1];
//
//        }
//
//        $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
//
//        while($instagram_id > 0) {
//
//            $remainder = $instagram_id % 64;
//            $instagram_id = ($instagram_id - $remainder) / 64;
//            $url_suffix = $alphabet[$remainder] . $url_prefix;
//
//            return $url_prefix . $url_suffix;
//        };
//    }

}
